name: "Publish"
on:
  create:
    branches:
      - master

jobs:
  release:
    name: Publish GitHub Actions to Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Publish GitHub Actions to Marketplace
        uses: technote-space/release-github-actions@v6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: 'Martin Nuc'
          COMMIT_EMAIL: 'martin@nuc.cz'
          CREATE_MAJOR_VERSION_TAG: false
          CREATE_MINOR_VERSION_TAG: false
          key: '.[!.]*,test,src,*.js,*.ts,*.json,CHANGELOG.md,_config.yml'
